txt = [];
percent = [];
waiting = []
frame = [];
pressed = []
vis = []
locX = [];
locY = [];
len = 0;
per_trigger = 80;
rate = 1;
time_limit = 30;
starttime = current_second;
endtime = starttime + time_limit;
time_left = endtime - starttime;